// ═══════════════════════════════════════════════════════════════
// 紫宸石箓 Zichen-Runelith — 商品数据层
// ═══════════════════════════════════════════════════════════════

const CATEGORIES = [
  { id: "love",    name_en: "Love & Romance",   name_zh: "异性缘多多", emoji: "💗", color: "#E8A0C8" },
  { id: "wealth",  name_en: "Wealth & Prosperity", name_zh: "红包鼓鼓", emoji: "🧧", color: "#C9A24B" },
  { id: "career",  name_en: "Career & Success",  name_zh: "事业顺顺", emoji: "📈", color: "#7FB8F0" },
  { id: "health",  name_en: "Health & Wellness", name_zh: "健康每一天", emoji: "🌿", color: "#8FD8B4" },
  { id: "sleep",   name_en: "Sleep & Peace",     name_zh: "睡眠一整晚", emoji: "🌙", color: "#7FA8E8" },
  { id: "protect", name_en: "Protection",        name_zh: "坏事滚远远", emoji: "🛡️", color: "#A99BE8" },
  { id: "study",   name_en: "Focus & Wisdom",    name_zh: "成绩好又好", emoji: "🎓", color: "#B8A4E8" },
  { id: "popular", name_en: "Trending",          name_zh: "人见人爱", emoji: "✨", color: "#E8D5A0" },
];

// ── 成品手串 ──────────────────────────
const PRODUCTS = [
  {
    id: 1,
    name_en: "Rose Quartz Heart Bracelet",
    name_zh: "粉晶爱心手串",
    price: 48,
    originalPrice: 58,
    emoji: "💗",
    tag_en: "Romance",
    tag_zh: "桃花",
    sales: 512,
    cat: "love",
    desc_en: "Natural rose quartz, promotes love and self-care. Each bead is hand-selected for its gentle pink hue.",
    desc_zh: "天然粉晶，促进爱情与自我关爱。每颗珠子手工挑选，色泽温柔。",
    sizes: [6, 8, 10, 12],
  },
  {
    id: 2,
    name_en: "Citrine Prosperity Bowl",
    name_zh: "黄水晶聚宝盆",
    price: 89,
    originalPrice: 108,
    emoji: "💛",
    tag_en: "Wealth",
    tag_zh: "招财",
    sales: 389,
    cat: "wealth",
    desc_en: "Natural citrine cluster, attracts abundance and prosperity. Perfect for your workspace.",
    desc_zh: "天然黄水晶簇，招财纳福。放在工作台上再合适不过。",
    sizes: [8, 10],
  },
  {
    id: 3,
    name_en: "Aquamarine Guardian Pendant",
    name_zh: "海蓝宝守护吊坠",
    price: 72,
    emoji: "💙",
    tag_en: "Peace",
    tag_zh: "平安",
    sales: 176,
    cat: "sleep",
    desc_en: "Genuine aquamarine, calms the mind and promotes restful sleep. A soothing companion.",
    desc_zh: "真正的海蓝宝，安抚心灵，促进安眠。温柔的守护伴侣。",
    sizes: [6, 8],
  },
  {
    id: 4,
    name_en: "Black Obsidian Shield",
    name_zh: "黑曜石平安扣",
    price: 36,
    emoji: "🖤",
    tag_en: "Protection",
    tag_zh: "辟邪",
    sales: 645,
    cat: "protect",
    desc_en: "Premium black obsidian, absorbs negative energy. A powerful protective talisman.",
    desc_zh: "优质黑曜石，吸收负面能量。强大的护身护身符。",
    sizes: [8, 10, 12],
  },
  {
    id: 5,
    name_en: "Moonstone Love Ring",
    name_zh: "月光石轻奢戒指",
    price: 66,
    emoji: "🌙",
    tag_en: "Romance",
    tag_zh: "浪漫",
    sales: 298,
    cat: "love",
    desc_en: "Rainbow moonstone with ethereal blue flash. Enhances intuition and romantic connections.",
    desc_zh: "彩虹月光石，带有空灵蓝光。增强直觉与浪漫缘分。",
    sizes: [6, 8],
  },
  {
    id: 6,
    name_en: "Smoky Quartz Focus Tower",
    name_zh: "茶晶能量塔",
    price: 58,
    emoji: "🤎",
    tag_en: "Focus",
    tag_zh: "稳运",
    sales: 142,
    cat: "study",
    desc_en: "Natural smoky quartz point, grounds energy and enhances concentration.",
    desc_zh: "天然茶晶柱，稳定能量，提升专注力。",
    sizes: [10, 12],
  },
  {
    id: 7,
    name_en: "Green Fluorite Energy Pillar",
    name_zh: "绿萤石能量柱",
    price: 62,
    emoji: "💚",
    tag_en: "Health",
    tag_zh: "专注",
    sales: 207,
    cat: "health",
    desc_en: "Natural green fluorite, purifies mind and body. Excellent for meditation spaces.",
    desc_zh: "天然绿萤石，净化身心。非常适合冥想空间。",
    sizes: [8, 10],
  },
  {
    id: 8,
    name_en: "Clear Quartz Pendulum",
    name_zh: "白水晶灵摆球",
    price: 42,
    emoji: "⚪",
    tag_en: "Purify",
    tag_zh: "净化",
    sales: 334,
    cat: "study",
    desc_en: "Pure clear quartz sphere, amplifies energy and intention. Essential for any crystal collection.",
    desc_zh: "纯净白水晶球，放大能量与意图。水晶收藏必备。",
    sizes: [6, 8, 10],
  },
  {
    id: 9,
    name_en: "Garnet Vitality Bracelet",
    name_zh: "石榴石红运手链",
    price: 54,
    emoji: "❤️",
    tag_en: "Vitality",
    tag_zh: "气血",
    sales: 421,
    cat: "health",
    desc_en: "Deep red garnet, boosts energy and vitality. A warm companion for cold days.",
    desc_zh: "深红石榴石，提升能量与活力。寒冷日子的温暖伴侣。",
    sizes: [6, 8, 10],
  },
  {
    id: 10,
    name_en: "Tourmaline Rainbow Bracelet",
    name_zh: "碧玺彩虹手串",
    price: 128,
    emoji: "🌈",
    tag_en: "Energy",
    tag_zh: "能量",
    sales: 156,
    cat: "popular",
    desc_en: "Multi-color tourmaline, balances all chakras. Each bracelet is uniquely colored.",
    desc_zh: "多色碧玺，平衡所有脉轮。每条手串色彩独一无二。",
    sizes: [8, 10],
  },
  {
    id: 11,
    name_en: "Lapis Wisdom Pendant",
    name_zh: "青金石智慧吊坠",
    price: 78,
    emoji: "🔷",
    tag_en: "Wisdom",
    tag_zh: "智慧",
    sales: 98,
    cat: "career",
    desc_en: "Premium lapis lazuli with gold pyrite inclusions. Enhances clarity and truth.",
    desc_zh: "优质青金石含黄铁矿内含物。增强清晰度与真实。",
    sizes: [8, 10],
  },
  {
    id: 12,
    name_en: "Red Agate Pixiu Pendant",
    name_zh: "红玛瑙貔貅吊坠",
    price: 68,
    emoji: "🔴",
    tag_en: "Wealth",
    tag_zh: "纳财",
    sales: 267,
    cat: "wealth",
    desc_en: "Carved red agate pixiu, traditional wealth-attracting charm. Handcrafted with care.",
    desc_zh: "红玛瑙貔貅雕刻，传统招财吉祥物。精心手工制作。",
    sizes: [8, 10],
  },
];

// ── DIY 珠子库 ──────────────────────────
// size 单位 mm，price 单位 USD/颗
const BEADS = [
  // 水晶类
  { id: "bd01", name_en: "Clear Quartz",     name_zh: "白水晶",   emoji: "⚪", size: 8,  price: 1.2, color: "#F0EDE8", cat: "crystal", element: "metal" },
  { id: "bd02", name_en: "Amethyst",         name_zh: "紫水晶",   emoji: "💜", size: 8,  price: 1.8, color: "#9B7EC8", cat: "crystal", element: "water" },
  { id: "bd03", name_en: "Citrine",          name_zh: "黄水晶",   emoji: "💛", size: 10, price: 2.4, color: "#E8C84B", cat: "crystal", element: "earth" },
  { id: "bd04", name_en: "Aquamarine",       name_zh: "海蓝宝",   emoji: "💙", size: 8,  price: 2.0, color: "#7FB8D8", cat: "crystal", element: "water" },
  { id: "bd05", name_en: "Black Obsidian",   name_zh: "黑曜石",   emoji: "🖤", size: 12, price: 1.5, color: "#2A2420", cat: "crystal", element: "water" },
  { id: "bd06", name_en: "Rose Quartz",      name_zh: "粉晶",     emoji: "💗", size: 8,  price: 1.4, color: "#F0B8C8", cat: "crystal", element: "fire" },
  { id: "bd07", name_en: "Smoky Quartz",     name_zh: "茶晶",     emoji: "🤎", size: 10, price: 1.6, color: "#8B7355", cat: "crystal", element: "earth" },
  { id: "bd08", name_en: "Green Fluorite",   name_zh: "绿萤石",   emoji: "💚", size: 8,  price: 1.3, color: "#7BC88C", cat: "crystal", element: "wood" },
  { id: "bd09", name_en: "Garnet",           name_zh: "石榴石",   emoji: "❤️", size: 6,  price: 1.8, color: "#A8324A", cat: "crystal", element: "fire" },
  { id: "bd10", name_en: "Moonstone",        name_zh: "月光石",   emoji: "🌙", size: 6,  price: 2.2, color: "#D8D4E0", cat: "crystal", element: "water" },
  { id: "bd11", name_en: "Tiger Eye",        name_zh: "虎眼石",   emoji: "🐯", size: 10, price: 1.5, color: "#C8A040", cat: "crystal", element: "earth" },
  { id: "bd12", name_en: "Lapis Lazuli",     name_zh: "青金石",   emoji: "🔷", size: 8,  price: 2.6, color: "#2E4A8B", cat: "crystal", element: "water" },
  { id: "bd13", name_en: "Jade",             name_zh: "翡翠",     emoji: "🟢", size: 8,  price: 3.0, color: "#5B9B6B", cat: "crystal", element: "wood" },
  { id: "bd14", name_en: "Labradorite",      name_zh: "拉长石",   emoji: "✨", size: 8,  price: 2.8, color: "#6B7B8B", cat: "crystal", element: "water" },
  { id: "bd15", name_en: "Carnelian",        name_zh: "红玛瑙",   emoji: "🟠", size: 10, price: 1.4, color: "#D06030", cat: "crystal", element: "fire" },
  { id: "bd16", name_en: "Lepidolite",       name_zh: "紫锂辉",   emoji: "💟", size: 8,  price: 2.4, color: "#C8A0D8", cat: "crystal", element: "water" },

  // 配饰类
  { id: "ac01", name_en: "Gold Spacer",      name_zh: "金色隔片", emoji: "⚙️", size: 4,  price: 0.8, color: "#C9A24B", cat: "accessory", element: "metal" },
  { id: "ac02", name_en: "Silver Spacer",    name_zh: "银色隔片", emoji: "⚙️", size: 4,  price: 0.6, color: "#C0C0C0", cat: "accessory", element: "metal" },
  { id: "ac03", name_en: "Gold Charm",       name_zh: "金色吊坠", emoji: "✨", size: 6,  price: 2.0, color: "#C9A24B", cat: "accessory", element: "metal" },
  { id: "ac04", name_en: "Silver Charm",     name_zh: "银色吊坠", emoji: "✨", size: 6,  price: 1.5, color: "#C0C0C0", cat: "accessory", element: "metal" },
  { id: "ac05", name_en: "Knot Guard",       name_zh: "结扣",     emoji: "🔒", size: 3,  price: 0.4, color: "#A09888", cat: "accessory", element: "metal" },
];

// ── 灵感设计（用户作品参考）──────────────────────────
const INSPIRATION_DESIGNS = [
  {
    id: "ins01",
    name_en: "Ocean Calm",
    name_zh: "海洋静谧",
    beads: ["bd04","bd04","bd04","bd04","bd04","bd04","bd04","bd04","bd04","bd10","bd01","bd10","bd04","bd04","bd04","bd04","bd04","bd04","bd04","bd04"],
    likes: 72,
    price: 42,
    style: "single",
  },
  {
    id: "ins02",
    name_en: "Sunset Glow",
    name_zh: "落日余晖",
    beads: ["bd03","bd15","bd06","bd03","bd15","bd06","bd03","bd15","bd06","bd03","bd15","bd06","bd03","bd15","bd06","bd03","bd15","bd06","bd03","bd15"],
    likes: 58,
    price: 38,
    style: "single",
  },
  {
    id: "ins03",
    name_en: "Mystic Night",
    name_zh: "神秘之夜",
    beads: ["bd02","bd05","bd12","bd02","bd05","bd12","bd02","bd05","bd12","bd02","bd05","bd12","bd02","bd05","bd12","bd02","bd05","bd12","bd02","bd05"],
    likes: 96,
    price: 48,
    style: "single",
  },
];
